### ISSUE TITLE
No code. And $eature request.

### ISSUE THREAD

**Issue by ghost** [Giganitris/FRC#1]
On your source forge page you said you moved to here but there is no code. Are you working on a new version or is the code you are planning on putting here the same as on the sourceforge page?

Also it says it has features from the real time corruptor but in the manuel it doesn't mention any. Is there a way to run the program so it randomly corrupts random bytes in real time?

Keep up the great work, me and my friends are having a great time using your program.

**Comment by Giganitris** [comment]
Haha that's wicked awesome! I had no idea people actually used my program!
I'm currently rewriting the program from scratch, it has a few kinks I need
to work out. It doesn't have any real-time capabilities yet, but it's
something I plan on adding. There's currently no way to corrupt bytes in
real time. You unfortunately have to corrupt the ROM first, then load it.

Honestly, if you know how to use the save feature, I'd love to try out the
corruptions you guys make and like. The switches load in chronological
order, so to save a corruption for sharing, type your -c switch first, then
the -s. The newly created file can then be loaded on the same or other roms
using -l.

By the way, are you running Windows or Linux, just curious.

**Comment by ghost** [comment]
Tbh i never use  the save feature, i find it easier to just write down the code for the corruption than to look up the file name for the  save and the load it in to the program.

I use it mostly on my armhf linux pc but i have used it on windows.

I have been trying to write my own own corruptor as a learning project, but editing binary files is going over my head, lol.

If it's not too much  trouble, could you document with comments whats going on in the code so i can understand what going on more. I mean on the new code. Thank you.

 Ill send some of my corruptions later. I've mostly been corrupting supermario bro 3 and pepsiman(for the ps1)

**Comment by Giganitris** [comment]
SMB3 produces some of my favourite corruptions, and the whole reason I'm rewriting it is so it works better and it's easier to read/edit. I'm looking forward to seeing the corruptions. Do you think I could somehow make it easier to use the save/load feature? I plan on making a graphical front-end for the corruptor. 

EDIT: If you'd like, you guys can send send me your preferred GUI designs, since I don't actually know how I'm going to design the GUI yet.

**Comment by ghost** [comment]
I think  adding a gui would make it easier to load saves. But if possible  id like it to be able to  still be able to use cli. On my arm pc i ussualy dont have a mouse hooked up, just a wireless keyboard and i am able to run and control the whole program with just the keyboard. A gui would make it alot easier to load them in succession.

Maybe have a drop down box in the gui that gets all the roms or saves in a specified folder(maybe have the directory paths for the rom/saves scan in a config file?) and let you pick the rom and corruption save.
Just some ideas, not sure how feasible they would be.

**Comment by Giganitris** [comment]
All of what you said sounds perfectly feasable. I'll try and include it all.

**Comment by ghost** [comment]
Thank you, keep up the great work and take you time no rush :D

**Comment by Giganitris** [comment]
Okay, thanks haha. I was worrying about when to release it.

**Comment by Giganitris** [comment]
Okay, I've just given the program support for multiple languages but now I've decided to rewrite the engine to execute plugins which will handle the corruption themselves. I could either use shared objects (DLL files) or bytecode files to do the job. DLL files are usually used in Windows programs but they're as dangerous as exe files, so I don't trust the too much, but the DLL route is by far the fastest, easiest and most flexible route. Bytecode files are interpreted by the program, not the machine, so it's extrewmely hard to make a malicious bytecode file. The problem with this, though, is that bytecode is usually used for very big projects and it'd take a long time to implement. I think you guys should have a say in how the program is made. What do you think?

**Comment by ghost** [comment]
thanks for letting me putting my input. I would like which ever method you prefer and that is platform agnostic(runs on any os). I assume the dll method would be windows only? As for time, honestly as long as the program is stable and robust, i don't care how long it takes. I understand you are doing this in your free time and have a life of your own. Take as much time as you need.

Also i was wondering if the program would support bigger roms such as the ps1(~700 mb). The original corrupter you made did.  What would the max file size be?

**Comment by Giganitris** [comment]
It should support files up to 4GiB, both corruptors should.  Plugins will be writen in C and then compiled into which ever file, depending on the OS. DLL's are for Windows, .so for Linux. The next release probably wont be too far from now.

**Comment by Giganitris** [comment]
Never mind. I honestly can't decide how to further design this thing. TYhere are so many different ways and it's hard to say which one's best. Honestly, feedback would be extremely helpful by either you or your friends. Everything helps.

**Comment by ghost** [comment]
What in particular would would like feed back on? I'll do my best to help. I'm almost done with my first semester with c++ in college. So my knowledge is pretty limited but i will do my best to help.

**Comment by Giganitris** [comment]
No problem. I've actually never taken a course in programing. I'm self-taught. What I'm thinking of, is how corruptions are handled. Should the methods of corruption be built into the program (like the last version) or external? I've personally been thinking of making it external, which leads me to the next question. Bytecode, DLL, script or (insert other method here)? Bytecode is just like an exe file, but it can't be run by the computer. My program has to interpret it for the computer, like Java. This allows me to run the program in a VM. Same thing goes for scripts, but I can't seem to find a library that makes it easier to control them. DLL's are like exe files, so the computer itself interprets them. This gives me very little control over them. A good reason why corruption methods should be handled externally is that it makes the corruptor way more flexible, like if someone discovers some algorithm that makes the ROMs glitches more enjoyable, it can easily be added to the corruptor by simply putting a file into a particular folder. 

I guess I can't really say exactly what kind of feedback I need.

**Comment by ghost** [comment]
Well if you cannot find a way to control and modularize the the program with dynamic librarys, you could just put each corruption method as a different function. The program would not be as flexible and you could not just drop a corruption method in a folder but you could easily add new corruption methods that arise to the code.

What kind of control are you looking for when it comes to the dll's?

**Comment by Giganitris** [comment]
Having each method simply as a function within the main program isn't a very flexible idea. Well, it doesn't take much to create a malicious dll file, since they are capable of doing everything an exe is capable of. I want to ensure that it doesn't have any weird side effects like that. I'd also prefer not do what the other corruptor did, which was to corrupt the byte which happened to be under the cursor when the time came. Allowing the program to move the cursor around and seek to certain positions in memory would be great, and I believe the RTC has that functionality built in. Giving the method that much flexibility while also reducing its ability to be malicious I think is a good idea. Maybe I'll just release the program with dll's first and then change the method in the next release.

**Comment by ghost** [comment]
Ok, i now understand, you want to limit the security flaws as much as possible while still being flexible. I have almost no knowledge when it comes to this subject. But I feel for now it would be fine just to be careful and only use dll files from people you trust as you have to do with any executable. And later if anyone can come up with a better, safer way do do this then it can be implemented.

For the ability to seek the cursor to any part of the memory would be a great feature, it would allow the program to go back and forth to certain addresses instead of just editing every so many bytes. It would make corrupting be able to be random without having to go through the rom multiple time just to move the cursor to the correct position.

**Comment by Giganitris** [comment]
I'm currently exporting the methods to their own source code right now. Hopefully, It'll be released either today or tomorrow. Which distros do you guys run?

**Comment by ghost** [comment]
I run debian jessie on my armhf pc. And window 10 64 bit on my laptop.
Thabks for you hardwork.

**Comment by Giganitris** [comment]
I honestly can't say that I'm very motivated to continue writing this. If you like, I can upload all of my code and then I can make you the owner of this repo. I can add comments to both the new code and the old code.

**Comment by ghost** [comment]
That would be cool. I usderstand and respect you decision. It would be great if you uploaded and comented the code. I would do my best to add festures or further develope the program and if not it would greatly help me understand c++ better. Thanks you for your hard work so far.

What features have been added to the code and what did you plan on adding but were unable to?

**Comment by Giganitris** [comment]
Thanks. This program makes more use of C over C++. I think older code uses more C++ though. I honestly prefer it this way. If I have any advice to give on programming in general, I'd advise that you read over these https://en.wikipedia.org/wiki/Unix_philosophy and this catb.org. They're great resources on programing effectively. I've tried my best to follow these guides when programming. 

I've added a feature which detects the language that your system is running and reads a file which contains the translation of this program. Two things that are missing is the save and load features, and corruption currently relies on a dynamically linked so file. I haven't wrtten any so files yet. Command switches are now written as -c, /c and --corrupt form now, so it's easier for all users. Id' say, that the new code is generally a lot cleaner.

**Comment by Giganitris** [comment]
After looking at the old code, I have to say that it's so poorly written,  that I'm unable to add new comments. The new code should hopefully be sufficiently commented.

**Comment by Giganitris** [comment]
Okay. To transfer the repository to you, you have to accept my request to become a collaborator.

**Comment by ghost** [comment]
Ok, thanks. Ill look at it when i have some time.
